export const DATE_OVERRIDE: string | null = null; // '2026-02-01'

// Demo days configuration - hardcode specific games for specific dates
// Format: 'YYYY-MM-DD': ['Game Title 1', 'Game Title 2', ...]
export const DEMO_DAYS: { [date: string]: string[] } = {
  '2026-01-28': [
    'Ghost of Tsushima',
    'The Legend of Zelda: Echoes of Wisdom',
    'Dave the Diver',
    'Mortal Kombat X',
    'Dark Souls II',
  ],
  '2026-01-29': [
    'Metaphor: ReFantazio',
    "Teenage Mutant Ninja Turtles: Shredder's Revenge",
    'Donkey Kong Country: Tropical Freeze',
    'Batman: Arkham Knight',
    'Dead or Alive 6',
  ],
  '2026-01-30': [
    'Dota 2',
    'Pentiment',
    'Skull and Bones',
    'Stranger of Paradise: Final Fantasy Origin',
    'Quantum Break',
  ],
  '2026-01-31': [
    'Neon White',
    "Tiny Tina's Wonderlands",
    'The Legend of Zelda: Tears of the Kingdom',
    'Hollow Knight',
    "Luigi's Mansion 3",
  ],
  '2026-02-02': [
    'Resident Evil 2',
    "Uncharted 4: A Thief's End",
    'Moonlighter',
    'The Legend of Zelda: A Link Between Worlds',
    'Xenoblade Chronicles X',
  ],
  '2026-02-03': [
    'Metal Gear Solid V: The Phantom Pain',
    'Remnant II',
    'Super Mario Bros. Wonder',
    'Yakuza: Like a Dragon',
    'Octopath Traveler II',
  ],
  '2026-02-04': [
    'Dynasty Warriors 9',
    'Sifu',
    'Battlefield 2042',
    'It Takes Two',
    'Granblue Fantasy: Relink',
  ],
  '2026-02-05': [
    "The Legend of Zelda: Link's Awakening",
    'The Elder Scrolls Online',
    'Shadow of the Tomb Raider',
    'Shovel Knight',
    'Fire Emblem Warriors: Three Hopes',
  ],
  '2026-02-06': [
    'Vampyr',
    'Rayman Legends',
    'Prince of Persia: The Lost Crown',
    'Fire Emblem Engage',
    'Mighty No. 9',
  ],
  '2026-02-07': [
    'Riders Republic',
    'Watch Dogs: Legion',
    "Hellblade: Senua's Sacrifice",
    'Nioh',
    'Deus Ex: Mankind Divided',
  ],
  '2026-02-13': [
    'Battlefield 4',
    'Project CARS 2',
    'Tropico 5',
    'Rogue Legacy',
    'Goat Simulator',
  ],
  '2026-02-14': [
    'God of War Ragnarok',
    'Mortal Kombat 11',
    'Thief',
    'Psychonauts 2',
    'Titanfall 2',
  ],
  '2026-02-15': [
    'The Thaumaturge',
    'Silent Hill 2',
    'Fallout 76',
    'Cocoon',
    'Bloodstained: Ritual of the Night',
  ],
  '2026-02-16': [
    'Rock Band 4',
    'Final Fantasy XV',
    'The Forgotten City',
    'Frostpunk 2',
    'Cuphead',
  ],
  '2026-02-17': [
    'Streets of Rage 4',
    'Ori and the Blind Forest',
    "Dragon's Dogma II",
    'Risk of Rain',
    'Titanfall',
  ],
  '2026-02-18': [
    'For Honor',
    'Darkest Dungeon',
    'Octopath Traveler',
    'Star Wars Battlefront',
    'Star Fox Zero',
  ],
  '2026-02-19': [
    'State of Decay 2',
    'Life is Strange: True Colors',
    'Star Wars Jedi: Fallen Order',
    'Pentiment',
    'Pikmin 4',
  ],
  '2026-02-20': [
    'Dying Light 2: Stay Human',
    'Remnant II',
    'Undertale',
    'OlliOlli World',
    'LEGO Marvel Super Heroes 2',
  ],
  '2026-02-21': [
    'Trine 4: The Nightmare Prince',
    'Stardew Valley',
    'Celeste',
    "Dragon's Dogma: Dark Arisen",
    'Gotham Knights',
  ],
  '2026-02-22': [
    'Just Cause 4',
    'Team Sonic Racing',
    'Ghost of Tsushima',
    'Attack on Titan',
    'Cult of the Lamb',
  ],
  '2026-02-23': [
    'Tell Me Why',
    'Detroit: Become Human',
    "Senua's Saga: Hellblade II",
    'Grid',
    'Injustice 2',
  ],
  '2026-02-24': [
    'Code Vein',
    'Kingdom Come: Deliverance',
    'Captain Toad: Treasure Tracker',
    'Monster Hunter Stories 2: Wings of Ruin',
    'Dead or Alive 6',
  ],
  '2026-02-25': [
    'Battleborn',
    'WarioWare: Get It Together!',
    'Metro Exodus',
    'Mighty No. 9',
    'Balan Wonderworld',
  ],
  '2026-02-26': [
    'Darksiders III',
    'Shenmue III',
    'F1 2017',
    'Wolfenstein: Youngblood',
    'Paper Mario: The Origami King',
  ],
  '2026-02-27': [
    'Mad Max',
    'SteamWorld Dig 2',
    'Hotline Miami 2: Wrong Number',
    'Crusader Kings III',
    'Mario Party 10',
  ],
  '2026-02-28': [
    'Returnal',
    'Octopath Traveler II',
    'Xenoblade Chronicles 3',
    'Tyranny',
    'The Witness',
  ],
  '2026-03-01': [
    'Moss',
    'Ratchet & Clank: Rift Apart',
    'Return to Monkey Island',
    'World of Final Fantasy',
    'Rage 2',
  ],
  '2026-03-02': [
    'Dirt Rally 2.0',
    'Visions of Mana',
    'Astral Chain',
    'A Plague Tale: Innocence',
    'Call of Duty: WWII',
  ],
  '2026-03-03': [
    'Life is Strange: Double Exposure',
    'Tekken 8',
    'Jurassic World Evolution 2',
    'Dead Island 2',
    'Super Mario Maker',
  ],
  '2026-03-04': [
    'Tropico 6',
    "Assassin's Creed Valhalla",
    'Xenoblade Chronicles 2',
    'Stellar Blade',
    'The King of Fighters XIV',
  ],
  '2026-03-05': [
    'Mario Party Superstars',
    'NEO: The World Ends with You',
    'Battletoads',
    'Enter the Gungeon',
    'Far Cry 6',
  ],
  '2026-03-06': [
    'Psychonauts 2',
    'Unicorn Overlord',
    'Fire Emblem Warriors: Three Hopes',
    'Star Wars: Squadrons',
    'Killing Floor 2',
  ],
  '2026-03-07': [
    'Sackboy: A Big Adventure',
    'Lies of P',
    'ReCore',
    'Rune Factory 5',
    'Minecraft Dungeons',
  ],
  '2026-03-08': [
    'Nioh 2',
    'Daemon X Machina',
    'Trials Rising',
    'Final Fantasy XV',
    'SteamWorld Heist II',
  ],
  '2026-03-09': [
    'Prince of Persia: The Lost Crown',
    'Battlefield 2042',
    'Tekken 8',
    'Crow Country',
    'Paper Mario: Color Splash',
  ],
  '2026-03-10': [
    'Alien: Isolation',
    'Dragon Quest Builders',
    'Unravel',
    'Outriders',
    'Nickelodeon All-Star Brawl',
  ],
  '2026-03-11': [
    "Yoshi's New Island",
    'Call of Duty: Ghosts',
    "Death's Door",
    'Rollerdrome',
    'Rayman Legends',
  ],
};

/*
'2026-02-09': [
    'Sea of Thieves',
    'Back 4 Blood',
    "Mirror's Edge Catalyst",
  ],

*/
