export const DATE_OVERRIDE: string | null = null; // '2026-02-01'

// Demo days configuration - hardcode specific games for specific dates
// Format: 'YYYY-MM-DD': ['Game Title 1', 'Game Title 2', ...]
export const DEMO_DAYS: { [date: string]: string[] } = {
  '2026-01-20': [
    'The Last of Us Part II',
    'Pentiment',
    'Valiant Hearts: The Great War',
    'Mighty No. 9',
    'Ace Combat 7: Skies Unknown',
  ],
  '2026-01-21': [
    'Rayman Legends',
    'Prince of Persia: The Lost Crown',
    'Yakuza: Like a Dragon',
    'Octopath Traveler II',
    'Moonlighter',
  ],
  '2026-01-22': [
    'Neon White',
    'Hollow Knight',
    'Suicide Squad: Kill The Justice League',
    "Luigi's Mansion 3",
    'Forza Horizon 3',
  ],
  '2026-01-23': [
    'Dota 2',
    'Owlboy',
    'A Hat in Time',
    'Visions of Mana',
    'Redfall',
  ],
  '2026-01-24': [
    'Star Wars Jedi: Survivor',
    "Teenage Mutant Ninja Turtles: Shredder's Revenge",
    'Donkey Kong Country: Tropical Freeze',
    'LEGO Jurassic World',
    'Silent Hill 2',
  ],
  '2026-01-25': [
    'The Legend of Zelda: Echoes of Wisdom',
    'SteamWorld Dig',
    'Skull and Bones',
    'Hot Wheels Unleashed',
    'Bayonetta 3',
  ],
  '2026-01-26': [
    'Ori and the Will of the Wisps',
    'Hyrule Warriors',
    'Splatoon 3',
    'Puyo Puyo Tetris',
    'Neverwinter',
  ],
  '2026-01-27': [
    "Assassin's Creed Valhalla",
    'Forza Horizon 4',
    'Mario Golf: Super Rush',
    'Tekken 8',
    'Sea of Stars',
  ],
  '2026-01-28': [
    'Monster Hunter Rise',
    'XCOM 2',
    'Dave the Diver',
    'Mortal Kombat X',
    'Dark Souls II',
  ],
  '2026-01-29': [
    'Super Mario 3D World',
    'Metaphor: ReFantazio',
    'A Plague Tale: Requiem',
    'Batman: Arkham Knight',
    'Dead or Alive 6',
  ],
  '2026-01-30': [
    'Hi-Fi Rush',
    'Animal Well',
    'Pokémon Sun and Moon',
    'Rocket League',
    "Tom Clancy's Ghost Recon: Wildlands",
  ],
  '2026-01-31': [
    'Deathloop',
    'Final Fantasy XV',
    'The Legend of Zelda: Tears of the Kingdom',
    'Call of Duty: Black Ops 6',
    'Tekken 7',
  ],
  '2026-02-02': [
    'Resident Evil 2',
    "Uncharted 4: A Thief's End",
    'Cyberpunk 2077',
    'Ghost of Tsushima',
    'Dishonored 2',
  ],
  '2026-02-03': [
    'Metal Gear Solid V: The Phantom Pain',
    'Remnant II',
    'Super Mario Bros. Wonder',
    'Bayonetta 2',
    'Peggle 2',
  ],
  '2026-02-04': [
    'Dynasty Warriors 9',
    'Sifu',
    'Battlefield 2042',
    'It Takes Two',
    'Granblue Fantasy: Relink',
  ],
  '2026-02-05': [
    "The Legend of Zelda: Link's Awakening",
    "Tiny Tina's Wonderlands",
    'Shadow of the Tomb Raider',
    'Shovel Knight',
    'Nintendo Switch Sports',
  ],
  '2026-02-06': [
    'Vampyr',
    'Sniper Elite 4',
    'Fire Emblem Engage',
    'Super Smash Bros. for Wii U',
    'SpongeBob SquarePants: The Cosmic Shake',
  ],
  '2026-02-07': [
    'Riders Republic',
    'Watch Dogs: Legion',
    "Hellblade: Senua's Sacrifice",
    'Nioh',
    'Deus Ex: Mankind Divided',
  ],
  '2026-02-08': [
    'Dead Rising 4',
    'Hitman 3',
    'South Park: The Stick of Truth',
    'Stranger of Paradise: Final Fantasy Origin',
    'Quantum Break',
  ],
  '2026-02-09': [
    'The Legend of Zelda: A Link Between Worlds',
    'Xenoblade Chronicles X',
    'Sea of Thieves',
    'Back 4 Blood',
    "Mirror's Edge Catalyst",
  ],
  '2026-02-13': [
    'Battlefield 4',
    'Project CARS 2',
    'Tropico 5',
    'Rogue Legacy',
    'Goat Simulator',
  ],
  '2026-02-14': [
    'God of War Ragnarok',
    'Mortal Kombat 11',
    'Thief',
    'Psychonauts 2',
    'Titanfall 2',
  ],
  '2026-02-15': [
    'The Thaumaturge',
    'Silent Hill 2',
    'Fallout 76',
    'Cocoon',
    'Bloodstained: Ritual of the Night',
  ],
  '2026-02-16': [
    'Rock Band 4',
    'The Elder Scrolls Online',
    'The Forgotten City',
    'Frostpunk 2',
    'Cuphead',
  ],
  '2026-02-17': [
    'Streets of Rage 4',
    'Ori and the Blind Forest',
    "Dragon's Dogma II",
    'Risk of Rain',
    'Titanfall',
  ],
  '2026-02-18': [
    'For Honor',
    'Darkest Dungeon',
    'Octopath Traveler',
    'Star Wars Battlefront',
    'Star Fox Zero',
  ],
  '2026-02-19': [
    'State of Decay 2',
    'Life is Strange: True Colors',
    'Star Wars Jedi: Fallen Order',
    'Pentiment',
    'Pikmin 4',
  ],
  '2026-02-20': [
    'Dying Light 2: Stay Human',
    'Remnant II',
    'Undertale',
    'OlliOlli World',
    'LEGO Marvel Super Heroes 2',
  ],
  '2026-02-21': [
    'Trine 4: The Nightmare Prince',
    'Stardew Valley',
    'Celeste',
    "Dragon's Dogma: Dark Arisen",
    'Gotham Knights',
  ],
  '2026-02-22': [
    'Just Cause 4',
    'Team Sonic Racing',
    'Ghost of Tsushima',
    'Attack on Titan',
    'Cult of the Lamb',
  ],
  '2026-02-23': [
    'Tell Me Why',
    'Detroit: Become Human',
    "Senua's Saga: Hellblade II",
    'Grid',
    'Injustice 2',
  ],
  '2026-02-24': [
    'Code Vein',
    'Kingdom Come: Deliverance',
    'Captain Toad: Treasure Tracker',
    'Monster Hunter Stories 2: Wings of Ruin',
    'Dead or Alive 6',
  ],
  '2026-02-25': [
    'Battleborn',
    'WarioWare: Get It Together!',
    'Metro Exodus',
    'Mighty No. 9',
    'Balan Wonderworld',
  ],
  '2026-02-26': [
    'Darksiders III',
    'Shenmue III',
    'F1 2017',
    'Wolfenstein: Youngblood',
    'Paper Mario: The Origami King',
  ],
  '2026-02-27': [
    'Mad Max',
    'SteamWorld Dig 2',
    'Hotline Miami 2: Wrong Number',
    'Crusader Kings III',
    'Mario Party 10',
  ],
  '2026-02-28': [
    'Returnal',
    'Octopath Traveler II',
    'Xenoblade Chronicles 3',
    'Tyranny',
    'The Witness',
  ],
  // Returnal
};
